apiVersion: in.saifali/v1alpha1
kind: KubeDeployer
metadata:
  name: wordpress-deployment
  namespace: default
spec:
  deploymentName: "wordpress-deployment"
  deploymentVersion: "wordpress:latest"
  replicas: 2
  ingress:
    enabled: true
    host: "wordpress.default.localhost"
    path: "/"
    pathType: "Prefix"
    tlsEnabled: false
  resources:
    memory:
      min: 512
      max: 1024
    cores:
      min: 1
      max: 2
  storage:
    size: "5Gi"
    storageClassName: "standard"
    accessMode: "ReadWriteOnce"
    mountPath: "/data/db"
  port: 80
  targetPort: 80
